name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.103'
    - run: dotnet build ./Source/bjdChangeFeed001/CosmosDbChangeFeed.csproj
    - uses: Azure/functions-action@v1
      id: fa
      with:
         app-name: bjdaction001
         publish-profile: ${{ secrets.AZURE_CREDENTIALS }}
         package: './output'

