name: CI

on: [push]

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@master

    - name: 'Login via Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Setup Dotnet 2.2.300
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.300'

    - name: 'Run dotnet build'
      shell: bash
      run: |
        pushd Source
        dotnet build --configuration Release --output=./ouput
        popd

    - name: 'Run Azure Functions Action'
      uses: Azure/functions-action@v1
      with:
        app-name: bjdaction001
        package: './Source/ouput'